version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: website_scraper_db
    environment:
      POSTGRES_USER: postgres        # Database username
      POSTGRES_PASSWORD: scrapingdemo  # Database password
      POSTGRES_DB: scraping_demo     # Default database name
    ports:
      - "5433:5432"                  # Map container's 5432 to host's 5433
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
